openapi: 3.0.3
info:
  title: quizDev
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://quizdev.test'
paths:
  /api/v1/test:
    get:
      summary: ''
      operationId: getApiV1Test
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "tu es connecté à l'api quiz dev"
      tags:
        - Endpoints
      security: []
  /api/v1/auth/register:
    post:
      summary: ''
      operationId: postApiV1AuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lastname:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: xvrfsuvnmu
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: unqidmpl
                password:
                  type: string
                  description: ''
                  example: qui
                role_id:
                  type: string
                  description: ''
                  example: '3'
                  enum:
                    - '2'
                    - '3'
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: tyshawn.sporer@example.net
              required:
                - lastname
                - name
                - password
                - role_id
                - email
      security: []
  /api/v1/auth/login:
    post:
      summary: ''
      operationId: postApiV1AuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: morar.roberto@example.net
                password:
                  type: string
                  description: ''
                  example: deserunt
              required:
                - email
                - password
      security: []
  /api/v1/profil:
    get:
      summary: ''
      operationId: getApiV1Profil
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/update/profil:
    put:
      summary: ''
      operationId: putApiV1UpdateProfil
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: heloise.walsh@example.org
                name:
                  type: string
                  description: ''
                  example: ratione
                lastname:
                  type: string
                  description: ''
                  example: quam
              required:
                - email
                - name
                - lastname
      security: []
  /api/v1/update/password:
    put:
      summary: ''
      operationId: putApiV1UpdatePassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                  description: ''
                  example: quia
                password:
                  type: string
                  description: ''
                  example: dolorum
              required:
                - current_password
                - password
      security: []
  /api/v1/logout:
    post:
      summary: ''
      operationId: postApiV1Logout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
